apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    http {
      server {
        listen 80;
        location / {
          default_type text/plain;
          return 200 "Hello from custom nginx config map\n";
        }
      }
    }
