apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: haproxy-cluster-role-devops
rules:
- apiGroups: [""]
  resources: ["Configmaps","secrets","services","endpoints","pods","nodes","namespaces","events","serviceaccounts"]
  verbs: ["get", "watch", "list", "create", "update", "delete", "patch"]
