apiVersion: v1
kind: Pod
metadata:
  name: servicepod
  namespace: default
spec:
  serviceAccountName: pvviewer
  containers:
    - name: container
      image: bitnami/kubectl:latest
      command: ["/bin/sh" , "-c" , "sleep 3600"]